name: veem-workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: build tests
      run: mkdir build && cmake -B build/ && cd build  && make
    - name: run tests
      run: ./build/tests/main_test

